# permissions for end users to view farshadawxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: awxoperator
    app.kubernetes.io/managed-by: kustomize
  name: farshadawx-viewer-role
rules:
- apiGroups:
  - cache.f4rsh4d
  resources:
  - farshadawxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.f4rsh4d
  resources:
  - farshadawxes/status
  verbs:
  - get
