# permissions for end users to edit projectawxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: awxoperator
    app.kubernetes.io/managed-by: kustomize
  name: projectawx-editor-role
rules:
- apiGroups:
  - cache.f4rsh4d
  resources:
  - projectawxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.f4rsh4d
  resources:
  - projectawxes/status
  verbs:
  - get
