---
- name: Add a host to AWX inventory
  awx.awx.host:
    name: "{{ host_name }}"  # Required: Name of the host
    description: "{{ host_description | default('Host added via playbook') }}"
    inventory: "{{ inventory_name }}"  # Required: Inventory name
    state: "{{ host_state | default('present') }}"  # Default state is 'present'
    controller_host: "{{ controller_host }}"  # AWX/Controller URL
    controller_username: "{{ controller_username }}"  # AWX/Controller username
    controller_password: "{{ controller_password }}"  # AWX/Controller password
    validate_certs: "{{ controller_verify_ssl | default(false) }}"  # SSL certificate validation
